import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const data=await mkdtemp(join(tmpdir(),'clara-tests-'));let server;
async function start(){server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'4279',DATA_DIR:data},stdio:'pipe'});await new Promise((ok,bad)=>{server.stdout.once('data',ok);server.once('error',bad);server.once('exit',c=>c&&bad(new Error('Server exit '+c)));});}
async function stop(){if(server.exitCode!==null)return;await new Promise(r=>{server.once('exit',r);server.kill();});}
function client(){let cookie='';return async(path,body,headers={})=>{const r=await fetch('http://127.0.0.1:4279/api'+path,{method:body?'POST':'GET',headers:{Cookie:cookie,...body&&{'Content-Type':'application/json'},...headers},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()};};}
await start();
test('Reserva, privacidad, persistencia y chat',async t=>{
 const visitor=client(),other=client(),admin=client();const s=await visitor('/status');let month=s.data.today.slice(0,7);let a=await visitor('/availability?month='+month);let date=Object.keys(a.data.days).find(d=>a.data.days[d].length>1);
 if(!date){const d=new Date(month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);month=d.toISOString().slice(0,7);a=await visitor('/availability?month='+month);date=Object.keys(a.data.days).find(d=>a.data.days[d].length>1);}
 const [time,otherTime]=a.data.days[date];let booking;
 await t.test('Valida los datos y el consentimiento',async()=>assert.equal((await visitor('/bookings',{date,time,name:'A',email:'bad',mode:'online',consent:false})).status,400));
 await t.test('Reserva y rechaza doble reserva',async()=>{const b={date,time,name:'Persona de prueba',email:'prueba@example.com',mode:'online',phone:'+34 600 000 000',privacyRead:true};const r=await visitor('/bookings',b);assert.equal(r.status,201);booking=r.data;assert.equal((await other('/bookings',b)).status,409);});
 await t.test('Aísla las reservas de cada visitante',async()=>{assert.deepEqual((await other('/bookings')).data,[]);assert.equal((await other('/bookings/'+booking.id+'/cancel',{})).status,404);assert.equal((await other('/bookings/'+booking.id+'/calendar')).status,404);});
 await t.test('Genera una cita descargable con horario UTC',async()=>{const r=await visitor('/bookings/'+booking.id+'/calendar');assert.equal(r.status,200);assert.match(r.data,/BEGIN:VCALENDAR/);const start=r.data.match(/DTSTART:(.*)/)[1].trim(),end=r.data.match(/DTEND:(.*)/)[1].trim();const parse=v=>new Date(v.replace(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z/,'$1-$2-$3T$4:$5:$6Z'));assert.equal(parse(end)-parse(start),20*60000);assert.match(r.data,/DTSTART:\d{8}T\d{6}Z/);});
 await t.test('Protege administración y peticiones externas',async()=>{assert.equal((await other('/admin/data')).status,401);assert.equal((await other('/admin/login',{password:'incorrecta'})).status,401);assert.equal((await other('/messages',{text:'bloqueado'},{Origin:'https://otra.example'})).status,403);});
 await t.test('Chat bidireccional y aislamiento de mensajes',async()=>{assert.equal((await visitor('/messages',{text:'Hola, prueba'})).status,201);assert.deepEqual((await other('/messages')).data,[]);await admin('/admin/login',{password:'consultorio-demo'});const d=(await admin('/admin/data')).data;assert.equal(d.messages[0].text,'Hola, prueba');assert.equal((await admin('/admin/reply',{session:d.messages[0].session,text:'Respuesta de prueba'})).status,201);assert.equal((await visitor('/messages')).data.at(-1).text,'Respuesta de prueba');});
 await t.test('Bloquea y libera horarios',async()=>{assert.equal((await admin('/admin/block',{date,time:otherTime,blocked:true})).status,200);assert.ok(!(await visitor('/availability?month='+month)).data.days[date].includes(otherTime));await admin('/admin/block',{date,time:otherTime,blocked:false});assert.ok((await visitor('/availability?month='+month)).data.days[date].includes(otherTime));});
 await t.test('Persiste reservas y mensajes al reiniciar',async()=>{await stop();await start();assert.equal((await visitor('/bookings')).data[0].id,booking.id);assert.equal((await visitor('/messages')).data.length,2);});
 await t.test('Cancelar libera la hora',async()=>{assert.equal((await visitor('/bookings/'+booking.id+'/cancel',{})).status,200);assert.ok((await visitor('/availability?month='+month)).data.days[date].includes(time));});
 await t.test('Rechaza fechas y mensajes inválidos',async()=>{assert.equal((await visitor('/availability?month=2026-99')).status,400);assert.equal((await visitor('/messages',{text:' '})).status,400);});
await t.test('First contact requires phone, privacy reading and online modality',async()=>{const data={date,time:otherTime,name:'Persona prueba',email:'test@example.com',phone:'+34 600 000 000',mode:'online',privacyRead:true};for(const patch of [{phone:''},{privacyRead:false},{mode:'presencial'}])assert.equal((await visitor('/bookings',{...data,...patch})).status,400);});
await t.test('Therapy requests persist separately and require valid fields',async()=>{const data={name:'Solicitud prueba',email:'solicitud@example.com',phone:'+34 600 000 000',mode:'presencial',privacyRead:true,therapyType:'pareja',availability:'Lunes 16 a 18 h, Madrid'};const before=(await visitor('/availability?month='+month)).data;for(const patch of [{phone:''},{privacyRead:false},{availability:''},{mode:'invalid'},{therapyType:'invalid'},{therapyType:undefined}])assert.equal((await visitor('/requests',{...data,...patch})).status,400);const r=await visitor('/requests',data);assert.equal(r.status,201);assert.equal(r.data.status,'pending');assert.deepEqual((await visitor('/availability?month='+month)).data,before);assert.equal((await visitor('/admin/request-status',{id:r.data.id,status:'contacted'})).status,401);await admin('/admin/login',{password:'consultorio-demo'});const requests=(await admin('/admin/data')).data.requests;assert.equal(requests[0].phone,data.phone);assert.equal(requests[0].therapy_type,'pareja');assert.equal(requests[0].privacy_version,'2026-09-21');assert.equal((await admin('/admin/request-status',{id:r.data.id,status:'contacted'})).status,200);assert.equal((await admin('/admin/data')).data.requests[0].status,'contacted');});

});
test.after(stop);

