import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleApi} from '../worker/index.js';
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(sql){return {bind(...v){return {async all(){return {results:sqlite.prepare(sql).all(...v)};},async first(){return sqlite.prepare(sql).get(...v)||null;},async run(){return {meta:sqlite.prepare(sql).run(...v)};}};}};}};
const env={DB,ADMIN_PASSWORD:'private-test-key'};
function client(ip){let cookie='';return async function(path,body){const r=await handleApi(new Request('https://demo.example/api'+path,{method:body?'POST':'GET',headers:{Cookie:cookie,'CF-Connecting-IP':ip,Origin:'https://demo.example',...body&&{'Content-Type':'application/json'}},body:body?JSON.stringify(body):undefined}),env);if(r.headers.get('set-cookie')){assert.match(r.headers.get('set-cookie'),/Secure/);cookie=r.headers.get('set-cookie').split(';')[0];}return {status:r.status,data:r.headers.get('content-type').includes('json')?await r.json():await r.text()};};}
test('Hosted database and API',async t=>{
 const a=client('client-a'),b=client('client-b'),admin=client('admin');const s=(await a('/status')).data;assert.equal(s.hosted,true);let month=s.today.slice(0,7);let days=(await a('/availability?month='+month)).data.days;let date=Object.keys(days).find(d=>days[d].length>1);if(!date){const d=new Date(month+'-01T12:00Z');d.setUTCMonth(d.getUTCMonth()+1);month=d.toISOString().slice(0,7);days=(await a('/availability?month='+month)).data.days;date=Object.keys(days).find(d=>days[d].length>1);}const [time,another]=days[date];let id,owner,outsider;
 await t.test('Concurrent reservations preserve slot uniqueness',async()=>{const data={date,time,name:'Test visitor',email:'test@example.com',mode:'online',phone:'+34 600 000 000',privacyRead:true};const results=await Promise.all([a('/bookings',data),b('/bookings',data)]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);id=results.find(r=>r.status===201).data.id;owner=results[0].status===201?a:b;outsider=results[0].status===201?b:a;assert.equal((await outsider('/bookings')).data.length,0);assert.equal((await outsider('/bookings/'+id+'/cancel',{})).status,404);});
 await t.test('No demo password works on hosted admin',async()=>{assert.equal((await admin('/admin/login',{password:'consultorio-demo'})).status,401);assert.equal((await admin('/admin/data')).status,401);assert.equal((await admin('/admin/login',{password:'private-test-key'})).status,200);});
 await t.test('Visitor messages reach professional and replies return',async()=>{await a('/messages',{text:'Mensaje de prueba'});assert.deepEqual((await b('/messages')).data,[]);const msgs=(await admin('/admin/data')).data.messages;assert.equal((await admin('/admin/reply',{session:msgs[0].session,text:'Respuesta de prueba'})).status,201);assert.equal((await a('/messages')).data.at(-1).text,'Respuesta de prueba');});
 await t.test('Blocked slots cannot be booked and cancellation releases slots',async()=>{assert.equal((await admin('/admin/block',{date,time:another,blocked:true})).status,200);assert.equal((await a('/bookings',{date,time:another,name:'Test',email:'test@example.com',mode:'online',phone:'+34 600 000 000',privacyRead:true})).status,409);assert.match((await owner('/bookings/'+id+'/calendar')).data,/BEGIN:VCALENDAR/);assert.equal((await owner('/bookings/'+id+'/cancel',{})).status,200);assert.ok((await a('/availability?month='+month)).data.days[date].includes(time));});
await t.test('First contact requires phone, privacy reading and online modality',async()=>{const data={date,time:another,name:'Persona prueba',email:'test@example.com',phone:'+34 600 000 000',mode:'online',privacyRead:true};for(const patch of [{phone:''},{privacyRead:false},{mode:'presencial'}])assert.equal((await a('/bookings',{...data,...patch})).status,400);});
await t.test('Therapy requests persist separately and require valid fields',async()=>{const data={name:'Solicitud prueba',email:'solicitud@example.com',phone:'+34 600 000 000',mode:'presencial',privacyRead:true,therapyType:'pareja',availability:'Lunes 16 a 18 h, Madrid'};const before=(await a('/availability?month='+month)).data;for(const patch of [{phone:''},{privacyRead:false},{availability:''},{mode:'invalid'},{therapyType:'invalid'},{therapyType:undefined}])assert.equal((await a('/requests',{...data,...patch})).status,400);const r=await a('/requests',data);assert.equal(r.status,201);assert.equal(r.data.status,'pending');assert.deepEqual((await a('/availability?month='+month)).data,before);assert.equal((await a('/admin/request-status',{id:r.data.id,status:'contacted'})).status,401);await admin('/admin/login',{password:'private-test-key'});const requests=(await admin('/admin/data')).data.requests;assert.equal(requests[0].phone,data.phone);assert.equal(requests[0].therapy_type,'pareja');assert.equal(requests[0].privacy_version,'2026-09-21');assert.equal((await admin('/admin/request-status',{id:r.data.id,status:'contacted'})).status,200);assert.equal((await admin('/admin/data')).data.requests[0].status,'contacted');});

});
test.after(()=>sqlite.close());

