import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,uniqueIndex,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),expires:integer('expires').notNull(),admin:integer('admin').default(0)});
export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),session:text('session').notNull(),date:text('date').notNull(),time:text('time').notNull(),name:text('name').notNull(),email:text('email').notNull(),phone:text('phone').notNull().default(''),duration:integer('duration').notNull().default(50),privacyVersion:text('privacy_version'),privacyReadAt:text('privacy_read_at'),mode:text('mode').notNull(),status:text('status').default('active'),created:text('created').notNull()},t=>[uniqueIndex('unique_slot').on(t.date,t.time).where(sql`${t.status} = 'active'`),index('bookings_session').on(t.session)]);
export const messages=sqliteTable('messages',{id:integer('id').primaryKey({autoIncrement:true}),session:text('session').notNull(),sender:text('sender').notNull(),text:text('text').notNull(),created:text('created').notNull()},t=>[index('messages_session').on(t.session)]);
export const blocked=sqliteTable('blocked',{date:text('date').notNull(),time:text('time').notNull()},t=>[primaryKey({columns:[t.date,t.time]})]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});

export const requests=sqliteTable('therapy_requests',{therapyType:text('therapy_type').notNull().default('unspecified'),id:text('id').primaryKey(),session:text('session').notNull(),name:text('name').notNull(),phone:text('phone').notNull(),email:text('email').notNull(),mode:text('mode').notNull(),availability:text('availability').notNull(),status:text('status').notNull().default('pending'),created:text('created').notNull(),privacyVersion:text('privacy_version').notNull(),privacyReadAt:text('privacy_read_at').notNull()},t=>[index('requests_session').on(t.session)]);
