import React,{useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ChatCircle} from '@phosphor-icons/react';
export const WHATSAPP='https://wa.me/34651197405?text=Hola%20Eugenia%2C%20encontr%C3%A9%20tu%20web%20y%20quer%C3%ADa%20hacerte%20una%20consulta%20antes%20de%20reservar%20la%20primera%20conversaci%C3%B3n';
const topics=[
 ['Modalidades de terapia','Eugenia ofrece psicoterapia para adultos y parejas, presencial en Madrid, en la zona de Metro Avenida de América, y online. Las sesiones duran entre 45 y 50 minutos. La frecuencia suele ser semanal y puede ajustarse a cada proceso.'],
 ['Primera conversación','Es una conversación online de 20 minutos, gratuita y sin compromiso, para conoceros, resolver dudas y valorar si tiene sentido iniciar un proceso. No constituye una sesión de psicoterapia ni una evaluación psicológica.'],
 ['Reservas','Puedes reservar una primera conversación gratuita en la agenda de Google Calendar disponible en esta web. Elige un horario y completa tus datos en Google. Recibirás la confirmación y el enlace de Google Meet. Para gestionar la reserva, consulta el correo de Google.'],
 ['Sobre la consulta','Eugenia Longhi es Psicóloga General Sanitaria, colegiada M-45148, con más de seis años de experiencia clínica. Trabaja desde una orientación psicodinámica y psicoanalítica, adaptando las herramientas a cada proceso.'],
];
export default function Assistant({Modal,onClose}){
 const [messages,setMessages]=useState([]);const end=useRef(null);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[messages]);
 return <Modal title="Asistente virtual de Consultorio Psi" onClose={onClose} className="chat-modal"><div className="chat-header"><div className="chat-avatar"><ChatCircle size={26}/></div><div><h3>Asistente virtual</h3><p>Información de Consultorio Psi</p></div></div><div className="chat-messages" role="log" aria-label="Información de la consulta" tabIndex={0}><div className="bubble system">Hola, soy el asistente virtual de Consultorio Psi. Puedo ayudarte con dudas sobre las modalidades de terapia, la primera conversación, las reservas y el funcionamiento de la consulta.</div><p className="chat-info">Respuestas informativas predefinidas. Inteligencia artificial pendiente de conexión.</p><div className="bubble system">Si prefieres hablar directamente con Eugenia, puedes escribirle por <a href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp</a>.</div>{messages.map((m,i)=><div className={'bubble '+(m.user?'outgoing':'incoming')} key={i}>{m.text}</div>)}<div ref={end}/></div><div className="assistant-actions"><div className="assistant-topics">{topics.map(([q,a])=><button key={q} onClick={()=>setMessages(m=>[...m,{user:true,text:q},{text:a}])}>{q}</button>)}</div><a className="text-button" href="#cita" onClick={onClose}>Primera conversación gratuita <ArrowUpRight/></a><a className="whatsapp-link" href={WHATSAPP} target="_blank" rel="noreferrer">Escribir directamente a Eugenia por WhatsApp <ArrowUpRight size={13}/></a><p className="small muted">Este asistente no ofrece atención psicológica ni está indicado para situaciones de urgencia.</p></div></Modal>;
}
